
name: Packege CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  packeg-build:
    name: packeg build and push
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
#         os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
    steps:
    - name: git pull
      uses: actions/checkout@v2
    - name: run a one-line script
      run: env
    - name: setting dotnet version 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: run pack
      run: |
        env
        echo "------------------------------------------------------"
        ls
        dotnet build
        dotnet pack -include-symbols  -p:PackageVersion=0.0.$GITHUB_RUN_ID
#         echo $GITHUB_JOB
#         dotnet pack  --include-symbols  -p:PackageVersion=0.0.$GITHUB_JOB
        
